In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats

In [3]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df_table = pd.crosstab(df['sex'], df['smoker'])
print(df_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [7]:
df_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [8]:
val = stats.chi2_contingency(df_table)

In [11]:
val
# array -> expected values

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [12]:
expected_values = val[3]

In [13]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

atleast 5 frequency is required for chi square